РК 2
go-park-mail-ru/2024_2_RPO pull request #12
Opened 2024-10-31 19:51 UTC by DeDxYk594

2024-11-01 18:29 UTC, reddiridabl666 requested changes

2024-11-01 18:29 UTC, reddiridabl666 commented on internal/pkg/auth/delivery/auth_delivery.go
> +		}
Лучше switch

2024-11-01 18:29 UTC, reddiridabl666 commented on internal/pkg/auth/repository/auth_repository.go
> +}
Плохо в одну структуру класть и редис, и постгрес. Стоит положить каждую СУБД в свой репозиторий, и эти два репозитория использовать уже на уровне бизнес-логики

2024-11-01 18:29 UTC, reddiridabl666 commented on internal/pkg/auth/repository/auth_repository.go
> +	ttl := 7 * 24 * time.Hour
В константу, стоит вынести из функции

2024-11-01 18:29 UTC, reddiridabl666 commented on internal/pkg/auth/repository/auth_repository.go
> +	return newUser, err
Ошибки от постгреса надо обрабатывать, чтобы возвращать соответствующий код ошибки. Может быть UniqueViolation какой-нибудь

2024-11-01 18:29 UTC, reddiridabl666 commented on internal/pkg/auth/repository/auth_repository.go
> +	query2 := `SELECT COUNT(*) FROM "user" WHERE email = $1`
Можно сделать одним запросом в базу. Чем меньше запросов - тем лучше

2024-11-01 18:29 UTC, reddiridabl666 commented on internal/pkg/auth/repository/auth_repository.go
> +}
К РК либо реализуйте, либо выпилите)

2024-11-01 18:29 UTC, reddiridabl666 commented on internal/pkg/auth/usecase/auth_uc.go
> +	sessionId = encrypt.GenerateSessionID()
У вас же кодстайл, что sessionID должно быть

2024-11-01 18:29 UTC, reddiridabl666 commented on internal/pkg/board/repository/boards.go
> +const defaultImageUrl = "/static/img/backgroundImage.png"
Такие штуки по идее в конфиге должны быть

2024-11-01 18:29 UTC, reddiridabl666 commented on internal/pkg/board/repository/boards.go
> +		board.BackgroundImageUrl = fmt.Sprintf("%s%s.%s", os.Getenv("USER_UPLOADS_URL"), fileUuid, fileExtension)
Вот репозиторий точно не должен ходить в env. Сделайте структуру конфига, которая собирается из env, прокиньте ее в репозиторий

2024-11-01 18:29 UTC, reddiridabl666 commented on internal/pkg/board/repository/boards.go
> +		if errors.Is(err, pgx.ErrNoRows) { // Может ли эта ошибка появиться?
Вроде не может. По-моему, она только в QueryRow

2024-11-01 18:29 UTC, reddiridabl666 commented on internal/pkg/board/repository/cards.go
> +// Что-то типа дополнительного уровня защиты
Вообще, должно хватать проверки прав на уровне бизнес-логики. Но ок, некритично

2024-11-01 18:29 UTC, reddiridabl666 commented on internal/pkg/board/repository/members.go
> +	}
Много логики для репозитория. Нельзя ли вынести в бизнес-логику?

2024-11-01 18:29 UTC, reddiridabl666 commented on internal/pkg/board/repository/members.go
> +	}
И это тоже в бизнес-логику

2024-11-01 18:29 UTC, reddiridabl666 commented on internal/pkg/board/usecase/board_uc.go
> +}
Можно сделать без init, просто литералом

2024-11-01 18:29 UTC, reddiridabl666 commented on internal/pkg/board/usecase/board_uc.go
> +}
Вроде же сделали продуктовые?)

2024-11-01 18:29 UTC, reddiridabl666 commented on internal/pkg/board/usecase/board_uc.go
> +	}
Сделать бы эти проверки проще. Вынести в функцию мб

2024-11-01 18:29 UTC, reddiridabl666 commented on internal/pkg/board/usecase/board_uc.go
> +		}
Тело условий одинаковое, объедините

2024-11-01 18:29 UTC, reddiridabl666 commented on internal/pkg/board/usecase/board_uc.go
> +		return err
Зачем..?

2024-11-01 18:29 UTC, reddiridabl666 commented on internal/pkg/middleware/csrf/csrf.go
> +}
Стоп, если у вас отдельный от сессионной куки csrf-токен, зачем его еще в куку класть?

2024-11-01 18:29 UTC, reddiridabl666 commented on internal/pkg/user/delivery/user_delivery.go
> +	r.ParseMultipartForm(10 << 20)
Давайте без шаманства, вынесите в константу

2024-11-01 18:29 UTC, reddiridabl666 commented on internal/pkg/user/delivery/user_delivery.go
> +	fmt.Fprintf(w, "Файл успешно загружен: %s\n", filename)
Почему строчку возвращаете? У нас все ответы в JSON

2024-11-01 18:29 UTC, reddiridabl666 commented on internal/pkg/user/delivery/user_delivery.go
> +	defer dst.Close()
Лучше сохранение файла вынести в бизнес-логику

2024-11-01 18:29 UTC, reddiridabl666 commented on internal/pkg/utils/environment/environment.go
> +
Как раз валидацию env можно сделать на этапе формирования структуры конфига

2024-11-01 18:52 UTC, DeDxYk594 commented on internal/pkg/board/usecase/board_uc.go
> +}
Забыл, точно (

2024-11-06 14:55 UTC, merged

2024-11-10 10:40 UTC, DeDxYk594 commented on internal/pkg/board/repository/members.go
> +	}
Нельзя

2024-11-10 10:41 UTC, DeDxYk594 commented on internal/pkg/board/repository/members.go
> +	}
Заменим на конструкцию WITH